name: generate monkeytype readme svg
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  download-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - uses: monkeytype-hub/monkeytype-readme@v1.0.0
        with:
          username: Annnt
          themes: serika_dark
          target-branch: monkeytype-readme
          github-token: ${{ secrets.GITHUB_TOKEN }}
          monkeytype-api-key: ${{ secrets.MONKEYTYPE_API_KEY }}
